In [2]:
import pandas as pd

In [3]:
data = pd.Series([10,20,30,40,50])
data

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
pd.DataFrame(data)

    0
0  10
1  20
2  30
3  40
4  50

In [5]:
data2 = {"Name" : ["Gaurav","Roshani","Mansi"],
         "Age" : [27,29,25],
         "Sex" : ["Male","Female","Female"]
         }

In [6]:
df = pd.DataFrame(data2)
df.shape

(3, 3)

In [7]:
df2 = pd.read_csv("Customers App 1301 to 1700.csv")
df2

                Name        Number
0            Babita   919429010971
1             Diana   919979619525
2      Vidya Parmar   919428189355
3      Hema Chauhan   919998219923
4         Shobhana    919099548364
..               ...           ...
395      Pooja Patel  918980448344
396  Shivani Gajera   919512799222
397           Ekta    919512899222
398   Franey Adalja   919723809892
399          Shipra   918107491595

[400 rows x 2 columns]

In [21]:
df2[["Name","Number"]]

                Name        Number
0            Babita   919429010971
1             Diana   919979619525
2      Vidya Parmar   919428189355
3      Hema Chauhan   919998219923
4         Shobhana    919099548364
..               ...           ...
395      Pooja Patel  918980448344
396  Shivani Gajera   919512799222
397           Ekta    919512899222
398   Franey Adalja   919723809892
399          Shipra   918107491595

[400 rows x 2 columns]

In [28]:
df2.loc(0)

In [26]:
df2.iloc[5:100,-1]

5     919429931993
6     919727715404
7     917567771391
8     919123456789
9     918140105553
          ...
95    919727630510
96    919712980687
97    917045356009
98    919913180760
99    919820080701
Name: Number, Length: 95, dtype: int64

In [10]:
df[df["Age"]>25]

      Name  Age     Sex
0   Gaurav   27    Male
1  Roshani   29  Female

In [11]:
(df["Name"]).str.len

In [12]:
df.isnull().sum()

Name    0
Age     0
Sex     0
dtype: int64

In [13]:
df.dropna()

      Name  Age     Sex
0   Gaurav   27    Male
1  Roshani   29  Female
2    Mansi   25  Female

In [14]:
df.fillna(0)

      Name  Age     Sex
0   Gaurav   27    Male
1  Roshani   29  Female
2    Mansi   25  Female

In [15]:
df.rename(columns={"Sex":"Gender"})

      Name  Age  Gender
0   Gaurav   27    Male
1  Roshani   29  Female
2    Mansi   25  Female

In [16]:
df["Smart"] = bool([1,0,1])
df

      Name  Age     Sex  Smart
0   Gaurav   27    Male   True
1  Roshani   29  Female   True
2    Mansi   25  Female   True

In [18]:
df.sort_values(["Age","Name"])

      Name  Age     Sex  Smart
2    Mansi   25  Female   True
0   Gaurav   27    Male   True
1  Roshani   29  Female   True

In [ ]:
df.duplicated()

0    False
1    False
2    False
dtype: bool

In [ ]:
df.isnull().sum()

Name     0
Age      0
Sex      0
Smart    0
dtype: int64

In [ ]:
df.drop_duplicates()

      Name  Age     Sex  Smart
0   Gaurav   27    Male   True
1  Roshani   29  Female   True
2    Mansi   25  Female   True

In [42]:
df.groupby("Sex")["Age"].count()

Sex
Female    2
Male      1
Name: Age, dtype: int64

In [49]:
df4 = pd.merge(df,df2,on="Name")

In [44]:
df

      Name  Age     Sex  Smart
0   Gaurav   27    Male   True
1  Roshani   29  Female   True
2    Mansi   25  Female   True

In [73]:
df6 = df[["Name","Age"]]

In [75]:
df6["Percentage"]=[90,80,100]

In [80]:
df6

      Name  Age  Percentage
0   Gaurav   27          90
1  Roshani   29          80
2    Mansi   25         100

In [79]:
df

      Name  Age     Sex  Smart  marks  lelo
0   Gaurav   27    Male   True     20    20
1  Roshani   29  Female   True     20    20
2    Mansi   25  Female   True     40    40

In [78]:
pd.merge(df,df6,on="Name")

      Name  Age_x     Sex  Smart  marks  lelo  Age_y  Percentage
0   Gaurav     27    Male   True     20    20     27          90
1  Roshani     29  Female   True     20    20     29          80
2    Mansi     25  Female   True     40    40     25         100

In [82]:
pd.concat([df,df6])

      Name  Age     Sex Smart  marks  lelo  Percentage
0   Gaurav   27    Male  True   20.0  20.0         NaN
1  Roshani   29  Female  True   20.0  20.0         NaN
2    Mansi   25  Female  True   40.0  40.0         NaN
0   Gaurav   27     NaN   NaN    NaN   NaN        90.0
1  Roshani   29     NaN   NaN    NaN   NaN        80.0
2    Mansi   25     NaN   NaN    NaN   NaN       100.0

In [83]:
df.value_counts()

Name     Age  Sex     Smart  marks  lelo
Gaurav   27   Male    True   20     20      1
Roshani  29   Female  True   20     20      1
Mansi    25   Female  True   40     40      1
Name: count, dtype: int64

In [88]:
df["Name"].nunique()

3

In [89]:
df.to_csv("output.csv")

In [97]:
df["Name"].str.contains("i")

0    False
1     True
2     True
Name: Name, dtype: bool

In [ ]:
s