In [1]:
import pandas as pd

In [3]:
data = pd.Series([10,20,30,40,50])
data

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
pd.DataFrame(data)

    0
0  10
1  20
2  30
3  40
4  50

In [5]:
data2 = {"Name" : ["Gaurav","Roshani","Mansi"],
         "Age" : [27,29,25],
         "Sex" : ["Male","Female","Female"]
         }

In [6]:
df = pd.DataFrame(data2)
df.shape

(3, 3)

In [7]:
df2 = pd.read_csv("Customers App 1301 to 1700.csv")
df2

                Name        Number
0            Babita   919429010971
1             Diana   919979619525
2      Vidya Parmar   919428189355
3      Hema Chauhan   919998219923
4         Shobhana    919099548364
..               ...           ...
395      Pooja Patel  918980448344
396  Shivani Gajera   919512799222
397           Ekta    919512899222
398   Franey Adalja   919723809892
399          Shipra   918107491595

[400 rows x 2 columns]

In [21]:
df2[["Name","Number"]]

                Name        Number
0            Babita   919429010971
1             Diana   919979619525
2      Vidya Parmar   919428189355
3      Hema Chauhan   919998219923
4         Shobhana    919099548364
..               ...           ...
395      Pooja Patel  918980448344
396  Shivani Gajera   919512799222
397           Ekta    919512899222
398   Franey Adalja   919723809892
399          Shipra   918107491595

[400 rows x 2 columns]

In [28]:
df2.loc(0)

In [26]:
df2.iloc[5:100,-1]

5     919429931993
6     919727715404
7     917567771391
8     919123456789
9     918140105553
          ...
95    919727630510
96    919712980687
97    917045356009
98    919913180760
99    919820080701
Name: Number, Length: 95, dtype: int64

In [10]:
df[df["Age"]>25]

      Name  Age     Sex
0   Gaurav   27    Male
1  Roshani   29  Female

In [11]:
(df["Name"]).str.len

In [12]:
df.isnull().sum()

Name    0
Age     0
Sex     0
dtype: int64

In [13]:
df.dropna()

      Name  Age     Sex
0   Gaurav   27    Male
1  Roshani   29  Female
2    Mansi   25  Female

In [14]:
df.fillna(0)

      Name  Age     Sex
0   Gaurav   27    Male
1  Roshani   29  Female
2    Mansi   25  Female

In [15]:
df.rename(columns={"Sex":"Gender"})

      Name  Age  Gender
0   Gaurav   27    Male
1  Roshani   29  Female
2    Mansi   25  Female

In [16]:
df["Smart"] = bool([1,0,1])
df

      Name  Age     Sex  Smart
0   Gaurav   27    Male   True
1  Roshani   29  Female   True
2    Mansi   25  Female   True

In [18]:
df.sort_values(["Age","Name"])

      Name  Age     Sex  Smart
2    Mansi   25  Female   True
0   Gaurav   27    Male   True
1  Roshani   29  Female   True

In [ ]:
df.duplicated()

0    False
1    False
2    False
dtype: bool

In [ ]:
df.isnull().sum()

Name     0
Age      0
Sex      0
Smart    0
dtype: int64

In [ ]:
df.drop_duplicates()

      Name  Age     Sex  Smart
0   Gaurav   27    Male   True
1  Roshani   29  Female   True
2    Mansi   25  Female   True

In [42]:
df.groupby("Sex")["Age"].count()

Sex
Female    2
Male      1
Name: Age, dtype: int64

In [49]:
df4 = pd.merge(df,df2,on="Name")

In [44]:
df

      Name  Age     Sex  Smart
0   Gaurav   27    Male   True
1  Roshani   29  Female   True
2    Mansi   25  Female   True

In [73]:
df6 = df[["Name","Age"]]

In [75]:
df6["Percentage"]=[90,80,100]

In [80]:
df6

      Name  Age  Percentage
0   Gaurav   27          90
1  Roshani   29          80
2    Mansi   25         100

In [79]:
df

      Name  Age     Sex  Smart  marks  lelo
0   Gaurav   27    Male   True     20    20
1  Roshani   29  Female   True     20    20
2    Mansi   25  Female   True     40    40

In [78]:
pd.merge(df,df6,on="Name")

      Name  Age_x     Sex  Smart  marks  lelo  Age_y  Percentage
0   Gaurav     27    Male   True     20    20     27          90
1  Roshani     29  Female   True     20    20     29          80
2    Mansi     25  Female   True     40    40     25         100

In [82]:
pd.concat([df,df6])

      Name  Age     Sex Smart  marks  lelo  Percentage
0   Gaurav   27    Male  True   20.0  20.0         NaN
1  Roshani   29  Female  True   20.0  20.0         NaN
2    Mansi   25  Female  True   40.0  40.0         NaN
0   Gaurav   27     NaN   NaN    NaN   NaN        90.0
1  Roshani   29     NaN   NaN    NaN   NaN        80.0
2    Mansi   25     NaN   NaN    NaN   NaN       100.0

In [83]:
df.value_counts()

Name     Age  Sex     Smart  marks  lelo
Gaurav   27   Male    True   20     20      1
Roshani  29   Female  True   20     20      1
Mansi    25   Female  True   40     40      1
Name: count, dtype: int64

In [88]:
df["Name"].nunique()

3

In [89]:
df.to_csv("output.csv")

In [97]:
df["Name"].str.contains("i")

0    False
1     True
2     True
Name: Name, dtype: bool

In [98]:
df.rename(columns={"Name":"name"})

      name  Age     Sex  Smart  marks  lelo
0   Gaurav   27    Male   True     20    20
1  Roshani   29  Female   True     20    20
2    Mansi   25  Female   True     40    40

In [115]:
df.loc[0:1,["Name","Age"]]

      Name  Age
0   Gaurav   27
1  Roshani   29

In [109]:
df.iloc[0:1,0]

0    Gaurav
Name: Name, dtype: str

In [1]:
# https://github.com/datasciencedojo/datasets
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

# https://github.com/mwaskom/seaborn-data/tree/master

iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"

# kaggle
kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [7]:
df = pd.read_csv(titanic_dataset_github_url)

In [8]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [19]:
df.loc[0:5:2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050,NaN,S

In [28]:
df.iloc[0,3]

'Braund, Mr. Owen Harris'

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [30]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [36]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [37]:
df.fillna(0)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,0,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0.0,1,2,W./C. 6607,23.4500,0,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,0,Q

In [41]:
df.drop_duplicates()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [44]:
df[["Name","Age"]]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [47]:
df[df["Sex"=="female"]] & df[df["Survived"==1]]["Name","Age"]

KeyError: False

In [48]:
sales_jan = pd.DataFrame({
    'Sales': [250, 400, 300]
}, index=['Store_A', 'Store_B', 'Store_C'])

sales_jan

         Sales
Store_A    250
Store_B    400
Store_C    300

In [53]:
sales_jan = pd.DataFrame({
    "sales":[250,400,500]
}, index=["St_a","St_b","Sat_c"])

sales_jan

       sales
St_a     250
St_b     400
Sat_c    500

In [59]:
sales_feb = pd.DataFrame({
    'Sales': [260, 310]
}, index=["St_a","Sat_c"])

sales_feb

       Sales
St_a     260
Sat_c    310

In [60]:
sales_fab_new = sales_feb.reindex(sales_jan.index)

In [61]:
sales_fab_new

       Sales
St_a   260.0
St_b     NaN
Sat_c  310.0

In [65]:
sales_fab_new["Sales"]-sales_jan["sales"]

St_a      10.0
St_b       NaN
Sat_c   -190.0
dtype: float64

In [66]:
source_a = pd.DataFrame({
    'Product': ['Laptop', 'Tablet', 'Phone'],
    'Price': [1000, 500, 800],
    'Stock': [30, 50, 100]
})

source_a

  Product  Price  Stock
0  Laptop   1000     30
1  Tablet    500     50
2   Phone    800    100

In [67]:
source_b = pd.DataFrame({
    'Price': [980, 520, 810],
    'Product': ['Laptop', 'Tablet', 'Phone']
})

source_b

   Price Product
0    980  Laptop
1    520  Tablet
2    810   Phone

In [72]:
aligned_b = source_b.reindex(columns=source_a.columns,fill_value=1)

In [73]:
aligned_b

  Product  Price  Stock
0  Laptop    980      1
1  Tablet    520      1
2   Phone    810      1

In [74]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Delhi', 'Mumbai', 'Chennai']
})

In [78]:
for index,row in df.iterrows():
    print(f"{row["Name"]} live in {row["City"]} & {row["Age"]} years old.")

Alice live in Delhi & 25 years old.
Bob live in Mumbai & 30 years old.
Charlie live in Chennai & 35 years old.

In [84]:
for row in df.itertuples():
    print(row)
    print(row.Index)
    print(f"{row.Name} live in {row.City} & {row.Age} years old.")

Pandas(Index=0, Name='Alice', Age=25, City='Delhi')
0
Alice live in Delhi & 25 years old.
Pandas(Index=1, Name='Bob', Age=30, City='Mumbai')
1
Bob live in Mumbai & 30 years old.
Pandas(Index=2, Name='Charlie', Age=35, City='Chennai')
2
Charlie live in Chennai & 35 years old.

In [91]:
for col in df.columns:
    print(col)
    print(df[col].values)

Name
<StringArray>
['Alice', 'Bob', 'Charlie']
Length: 3, dtype: str
Age
[25 30 35]
City
<StringArray>
['Delhi', 'Mumbai', 'Chennai']
Length: 3, dtype: str

In [94]:
df["Category"] = df["Age"].apply(lambda age : "Young" if age < 30 else "Old")
df

      Name  Age     City Category
0    Alice   25    Delhi    Young
1      Bob   30   Mumbai      Old
2  Charlie   35  Chennai      Old

In [96]:
df["Zone"] = df["City"].apply(lambda city: "Danger" if city=="Delhi" else "Healthy")
df

      Name  Age     City Category     Zone
0    Alice   25    Delhi    Young   Danger
1      Bob   30   Mumbai      Old  Healthy
2  Charlie   35  Chennai      Old  Healthy

In [97]:
def check(row):
    city = row["City"]
    Age = row["Age"]
    if city=="Delhi":
        if Age < 30:
            return True
        else: return False
    else: 
        return False

In [99]:
df["Delhi and young"] = df.apply(check, axis=1)

In [100]:
df["Delhi and young"]

0     True
1    False
2    False
Name: Delhi and young, dtype: bool

In [103]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset_github_url)
df.sort_values(by="Age").head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S

In [ ]:
df["Age"] = df["Age"].fillna(0).astype("int64")

0      22
1      38
2      26
3      35
4      35
       ..
886    27
887    19
888     0
889    26
890    32
Name: Age, Length: 891, dtype: int64

In [114]:
df.sort_values(by=['Pclass', 'Fare'],ascending=[True,False],axis=0)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35,0,0,PC 17755,512.3292,B101,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263.0000,C23 C25 C27,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23,3,2,19950,263.0000,C23 C25 C27,S
...,...,...,...,...,...,...,...,...,...,...,...,...
378,379,0,3,"Betros, Mr. Tannous",male,20,0,0,2648,4.0125,NaN,C
179,180,0,3,"Leonard, Mr. Lionel",male,36,0,0,LINE,0.0000,NaN,S
271,272,1,3,"Tornquist, Mr. William Henry",male,25,0,0,LINE,0.0000,NaN,S
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19,0,0,LINE,0.0000,NaN,S
597,598,0,3,"Johnson, Mr. Alfred",male,49,0,0,LINE,0.0000,NaN,S

In [115]:
df2 = df.set_index('PassengerId')

In [116]:
df2.sort_index()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,NaN,Q

In [118]:
df[sorted(df.columns)]

,Age,Cabin,Embarked,Fare,Name,Parch,PassengerId,Pclass,Sex,SibSp,Survived,Ticket
0,22,NaN,S,7.2500,"Braund, Mr. Owen Harris",0,1,3,male,1,0,A/5 21171
1,38,C85,C,71.2833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,2,1,female,1,1,PC 17599
2,26,NaN,S,7.9250,"Heikkinen, Miss. Laina",0,3,3,female,0,1,STON/O2. 3101282
3,35,C123,S,53.1000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,4,1,female,1,1,113803
4,35,NaN,S,8.0500,"Allen, Mr. William Henry",0,5,3,male,0,0,373450
...,...,...,...,...,...,...,...,...,...,...,...,...
886,27,NaN,S,13.0000,"Montvila, Rev. Juozas",0,887,2,male,0,0,211536
887,19,B42,S,30.0000,"Graham, Miss. Margaret Edith",0,888,1,female,0,1,112053
888,0,NaN,S,23.4500,"Johnston, Miss. Catherine Helen ""Carrie""",2,889,3,female,1,0,W./C. 6607
889,26,C148,C,30.0000,"Behr, Mr. Karl Howell",0,890,1,male,0,1,111369
890,32,NaN,Q,7.7500,"Dooley, Mr. Patrick",0,891,3,male,0,0,370376

# Date 28-02-2026 Practice

In [3]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset_github_url)

In [5]:
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [7]:
df['Name'].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [9]:
df['Name'].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: str

In [10]:
df['Name'].str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [11]:
df['Name'].str.title()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [13]:
df['Name'].str.replace('Mr.','Sir').head()

0                              Braund, Sir Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Sir William Henry
Name: Name, dtype: str

In [15]:
df.loc[1,"Name"]

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [22]:
start = df.loc[1,"Name"].find('(')
end = df.loc[1,"Name"].find(')')

df.loc[1,'Name'][0:start]+df.loc[1,'Name'][end:-1]

'Cumings, Mrs. John Bradley '

In [25]:
def remove_substring(name):
    start = name.find('(')
    end = name.find(')')

    return name[0:start]+name[end+1:]

refined_df = df['Name'].apply(remove_substring)

refined_df.head()

0      Braund, Mr. Owen HarriBraund, Mr. Owen Harris
1                        Cumings, Mrs. John Bradley
2        Heikkinen, Miss. LainHeikkinen, Miss. Laina
3                      Futrelle, Mrs. Jacques Heath
4    Allen, Mr. William HenrAllen, Mr. William Henry
Name: Name, dtype: str

In [26]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [30]:
df['Name'].str.replace(r'\(.*\)','',regex=True)

0                       Braund, Mr. Owen Harris
1                   Cumings, Mrs. John Bradley
2                        Heikkinen, Miss. Laina
3                 Futrelle, Mrs. Jacques Heath
4                      Allen, Mr. William Henry
                         ...
886                       Montvila, Rev. Juozas
887                Graham, Miss. Margaret Edith
888    Johnston, Miss. Catherine Helen "Carrie"
889                       Behr, Mr. Karl Howell
890                         Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [31]:
df['Name'][0]

'Braund, Mr. Owen Harris'

In [37]:
df['Name'].str.split(',')[0]

['Braund', ' Mr. Owen Harris']

In [59]:
df['Name'].str.split().str[0]

0         Braund,
1        Cumings,
2      Heikkinen,
3       Futrelle,
4          Allen,
          ...
886     Montvila,
887       Graham,
888     Johnston,
889         Behr,
890       Dooley,
Name: Name, Length: 891, dtype: object

In [60]:
df['Name'].str.find('Mr')

0       8
1       9
2      -1
3      10
4       7
       ..
886    -1
887    -1
888    -1
889     6
890     8
Name: Name, Length: 891, dtype: int64

In [62]:
df['Name'].str.contains("Miss").sum()

np.int64(182)

In [63]:
df['Name'].str.contains("Mr.").sum()

np.int64(647)

In [64]:
data = {
    'Name': [
        'John Doe', 'Jane Smith', 'Emily Johnson',
        'Robert Brown', 'Anna-Marie Lee'
    ],
    'Email': [
        'john@example.com', 'jane.smith@work.org',
        'emily_j@data.net', 'robertb@yahoo.com',
        'anna.lee@company.co'
    ]
}

In [65]:
df = pd.DataFrame(data)

In [66]:
df.head()

             Name                Email
0        John Doe     john@example.com
1      Jane Smith  jane.smith@work.org
2   Emily Johnson     emily_j@data.net
3    Robert Brown    robertb@yahoo.com
4  Anna-Marie Lee  anna.lee@company.co

In [77]:
df['Name'].str.pad(width=20, side='left', fillchar='-')

0    ------------John Doe
1    ----------Jane Smith
2    -------Emily Johnson
3    --------Robert Brown
4    ------Anna-Marie Lee
Name: Name, dtype: str

In [84]:
df["Email"].str.pad(width=45,side="left",fillchar=".")

0    .............................john@example.com
1    ..........................jane.smith@work.org
2    .............................emily_j@data.net
3    ............................robertb@yahoo.com
4    ..........................anna.lee@company.co
Name: Email, dtype: str

In [85]:
class_data = {
    "Name" : ["A", "B", "C", "D"],
    "Groups" : ["G1", "G2", "G3", "G4"]
}

In [88]:
class_df = pd.DataFrame(class_data)
class_df

  Name Groups
0    A     G1
1    B     G2
2    C     G3
3    D     G4

In [ ]:
class_df["Group_cat"] = pd.Categorical(class_df["Groups"],categories=class_df["Groups"],ordered=True)

In [90]:
class_df["Group_cat"].info

<bound method Series.info of 0    G1
1    G2
2    G3
3    G4
Name: Group_cat, dtype: category
Categories (4, str): ['G1' < 'G2' < 'G3' < 'G4']>

In [91]:
class_df["Group_cat"].cat.categories

Index(['G1', 'G2', 'G3', 'G4'], dtype='str', name='Groups')

In [95]:
class_df["Group_cat"] > "G3"

0    False
1    False
2    False
3     True
Name: Group_cat, dtype: bool

In [102]:
df = pd.read_csv(titanic_dataset_github_url)

In [103]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [105]:
df['Embarked'] = df['Embarked'].fillna("N")

In [106]:
df['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', 'N']
Length: 4, dtype: str

In [107]:
df['Embarked'].isnull().sum()

np.int64(0)

In [108]:
df['Embarked'] = df['Embarked'].astype("category")

In [110]:
df['Embarked'].cat.codes

0      3
1      0
2      3
3      3
4      3
      ..
886    3
887    3
888    3
889    0
890    2
Length: 891, dtype: int8

In [114]:
df['Sex'].astype('category').cat.codes

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Length: 891, dtype: int8

In [149]:
df = pd.DataFrame({
    'event': ['Concert', 'Conference', 'Wedding'],
    'date': ['2025-01-01', '2025-03-15', '2025-07-20']
})

In [150]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   event   3 non-null      str
 1   date    3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [151]:
df

        event        date
0     Concert  2025-01-01
1  Conference  2025-03-15
2     Wedding  2025-07-20

In [152]:
df['Pandas_date'] = pd.to_datetime(df["date"])

In [121]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   event        3 non-null      str
 1   date         3 non-null      str
 2   Pandas_date  3 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes

In [132]:
df['Pandas_date'].dt.day_of_year

0      1
1     74
2    201
Name: Pandas_date, dtype: int32

In [134]:
df[df["Pandas_date"].between('2025-01-01', '2025-06-01')]

        event        date Pandas_date
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15

In [143]:
pd.date_range(start="2026-05-01", end='2027-03-10',freq="D")

DatetimeIndex(['2026-05-01', '2026-05-02', '2026-05-03', '2026-05-04',
               '2026-05-05', '2026-05-06', '2026-05-07', '2026-05-08',
               '2026-05-09', '2026-05-10',
               ...
               '2027-03-01', '2027-03-02', '2027-03-03', '2027-03-04',
               '2027-03-05', '2027-03-06', '2027-03-07', '2027-03-08',
               '2027-03-09', '2027-03-10'],
              dtype='datetime64[us]', length=314, freq='D')

In [153]:
df['next_week'] = df['Pandas_date'] + pd.Timedelta(days=7)

In [155]:
pd.Timestamp.today()

Timestamp('2026-05-23 16:19:06.756450')